version: '3'

services:

  nats-server:
    image: nats:latest
    # Exponemos distintos puertos para que las conexiones externas puedan acceder al servidor NATS
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  products-ms: 
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    depends_on:
      - nats-server
  orders-ms:
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-database:5432/ordersdb?schema=public
      - PRODUCTS_MICROSERVICE_HOST=products-ms
      - PRODUCTS_MICROSERVICE_PORT=3001
    depends_on:
      - orders-db
  orders-db:
    container_name: orders-database
    image: postgres:16.2
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb